project:
  type: website
  output-dir: docs

website:
  title: "Boyi Guo (郭博逸), PhD"
  favicon: "img/Boyi_Guo_20190924.jpeg"
  navbar:
    left:
      - icon: house-door-fill
        href: https://boyi-guo.com
        aria-label: Home
      - href: https://www.overleaf.com/read/gdttrkmmwncb#4463ee
        text: CV
      # - about.qmd
      - projects.qmd
      - software.qmd
      - blog.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
