project:
  type: website
  output-dir: docs

website:
  title: "Boyi Guo (郭博逸), PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



