project:
  type: website
  output-dir: docs

website:
  title: "Boyi Guo (郭博逸), PhD"
  favicon: "img/Boyi_Guo_20190924.jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



