project:
  type: website
  output-dir: docs

website:
  title: "Boyi Guo (郭博逸), PhD"
  favicon: "img/Boyi_Guo_20190924.jpeg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: https://www.overleaf.com/read/gdttrkmmwncb#4463ee
        text: CV
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



