---
title: "Progression Report 20200129"
date: 2020-01-29
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Currently we are encrountering a challenge when designing the method, which is how to calculate se for the estimates. As suggested by Dr. Yi, we could go back to rstanarm and see how they did it, which is pretty much rely on the important resampling method. 

Another difficulty that is associated with using hessian matrix is the normality assumption. However, it is extremely releasitic for our model set up, where some estimate have a range between 0 and 1. So some other transformation for those estimates are necessary.

If neither of this path works out, we can try a two-step approach where we can use current algorithm to get the estimates. and contruct a new model that is based on the hyperparameters and calculate the betas and their se.

Meanwhile, Dr. Yi informed me about his improvement in BhGLM, which he set up for the network incorporated analysis, where the model set up is similar. I should at least start to focus on the simulation, which i did in the later of the week. I run simulations, however the evaluating metrics should be better considered. I was examing sensitivity and specificity as evaluating variable selection in a normal high dimensional setting. However, in our case of evaluating the network perspective. it is not the best measure to use. As a result, the performance is extremely similar to previous method, and barely see imporvemtn. Dr. Yi advised me to use other metrics that could reflect the correlation structure of the data, i.e. select the variables in a groups, all  of them. Meanwhile, he encourages me to go over the paper,EMVS and stingo papers to refer to their simulation criteria. Meanwhile, we should also evaluate the prediction performance other than the vairbale selection.

In terms of the simulation results, the smaller setting take 4-5 hours, will the larger setting takes more than 10 hours, and didn't finish, since I set up the simulation time to be less than 10 hours.



Actionable Items:
1. Check Imporantance sampling implementation in rstanarm, and refer it back to Bayesian Data analysis for understanding.
2. Remove the estimates that doesn't follow normal distribution when calculating se/inverting on Hessian.
3. Or possibly calculate the trasformation of the non-normal distributed estimates.
4. Always thinking baout the two step approach and keep it as an options
5. Understand or think about explaining the choice of $\phi$ in the model set up, and possibly evaluate the value of it, as 1 or 2 or something else.
5. Understand the update network and update group function in  BhGLM
6. Put the model set up on paper, and understand Dr. Yi's improvement of the code
7. Understand Dr. Yi's most recent update of the package
8. Summarize the simulation results
9. find the proper evaluation criteria for the simulation. reading the EMVS and Stingo papers.
10. and stand the grouping function and make sure what it does.


